### ISSUE TITLE
create setup.py script for configuration endpoints

### ISSUE THREAD

**Issue by abungay** [talos-org/server#17]
Make a setup.py script so that the user doesn't have to manually figure out what the dependencies are and install them one by one with pip.

**Comment by yeskunall** [comment]
As I mentioned in #2, I’d rather have all the dependencies in a `requirements.txt` file so we can just do this: `pip install -r requirements.txt`.

I guess my question is: what’s the benefit of this `setup.py` script over having a `requirements.txt` file?

**Comment by zaidoon1** [comment]
requirements.txt has been created.
