### ISSUE TITLE
Set up project

### ISSUE THREAD

**Issue by yeskunall** [talos-org/server#2]
Hey @talos-org/back-end, you guys need to start thinking about setting up a project structure now. Here’s a list you guys need to work on in the near future:

- [x] Create a LICENSE file
> Just copy [this](https://github.com/talos-org/client/blob/master/LICENSE).

- [x] Create a `.gitignore`
> Use [this](https://www.gitignore.io/api/python) as a template and add more stuff to it as necessary. This means removing any files that you pushed to git accidentally.

- [x] Create a `requirements.txt` file
> See [this](https://docs.python-guide.org/writing/structure/#requirements-file).

- [x] Update the README with installation instructions, along with any dev, env, or tooling required to make things work (see below)

- [x] Set up a `virtualenv`
> See [this](https://docs.python-guide.org/dev/virtualenvs/). Also see [pipenv](https://pipenv.readthedocs.io/en/latest/).

Ref: [Structuring Your Project, The Hitchhiker’s Guide to Python](https://docs.python-guide.org/writing/structure/)

**Comment by yeskunall** [comment]
@zaidoon1 I don’t think this should be put in `Icebox`. Think about when we’ll finally decide to package these changes into an app and test it on the VMs. It won’t work without some of the above things above. Even better yet, I cannot test these changes you’re making because I don’t know the dependencies, or even how this works.

Please think about that and assign this a better priority. Thanks!

**Comment by yeskunall** [comment]
@talos-org/back-end I’m labelling this as `critical`. @talos-org/front-end needs this done right away. This is urgent.

**Comment by zaidoon1** [comment]
README has been updated to include setup instructions
