### ISSUE TITLE
Connect to admin node not working

### ISSUE THREAD

**Issue by darshgrewal** [talos-org/server#38]
Connect to admin node is not working

/nodes/connect_to_admin_node
intput:

{
  "admin_node_address": "multichaind chain1@10.142.0.4:2875"
}

output:

{
  "errors": {
    "adminNodeAddress": "'adminNodeAddress' is a required property"
  },
  "message": "Input payload validation failed"
}

**Comment by zaidoon1** [comment]
fixed in #39
