### ISSUE TITLE
Plumbum timeout not working

### ISSUE THREAD

**Issue by zaidoon1** [talos-org/server#7]
When specifying a timeout for a Plumbum command. Plumbum ignores the timeout and continues polling for an output from a command indefinitely

**Comment by zaidoon1** [comment]
Plumbum hasn't fixed this bug since 2017 and as such it was decided to remove this library and to use the standard subprocess library that is bundled with Python

**Comment by yeskunall** [comment]
One thing I would suggest is looking into fixing the bug by modifying their
source code. If we find the fix is simple enough, then we can just make a
fork of Plumbum with our fixes pushed to it and then use our version of
Plumbum in Talos.

**Comment by zaidoon1** [comment]
I evaluated all the functions we need from the Plumbum library and realized that we are not using any of the advanced features that it offers. Therefore, it's best to reduce the number of dependencies and use the standard library.
